services:
  app:
    env_file:
      - .env
    image: develop_image:latest
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.config/nvim/:/root/.config/nvim/
      - .:/app/
    command: /app/run_dev_server.sh
    ports:
      - 3000:3000
      - 5173:5173
    tty: true
  # editior:
  #   image: my_nvim:basic
  #   volumes:
  #     - ./word_note/:/var/src
  #     - /home/water/develop/my_nvim/ruby/:/root/.config/nvim/
  #   tty: true
